### ISSUE TITLE
Tests on master fail

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.contacts#55] opened 2017-07-07 14:59 UTC
If I clone `ftw.contacts`, do a buildout and then run `bin/test` the tests fail with 2 failures:
```
Failure in test test_restrict_contacts_with_searchable_text (ftw.contacts.tests.test_contact_folder_reload.TestContactFolderReloadView)
Traceback (most recent call last):
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/raphael/Plone/eggs/ftw.testbrowser-1.25.0-py2.7.egg/ftw/testbrowser/__init__.py", line 41, in test_function
    return func(self, *args, **kwargs)
  File "/Users/raphael/projects/newcontacts/ftw/contacts/tests/test_contact_folder_reload.py", line 160, in test_restrict_contacts_with_searchable_text
    self.assertEqual(1, data.get('max_contacts'))
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 521, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 514, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0

    18/92 (19.6%)

Failure in test test_search_with_special_chars (ftw.contacts.tests.test_contact_folder_reload.TestContactFolderReloadView)
Traceback (most recent call last):
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/raphael/Plone/eggs/ftw.testbrowser-1.25.0-py2.7.egg/ftw/testbrowser/__init__.py", line 41, in test_function
    return func(self, *args, **kwargs)
  File "/Users/raphael/projects/newcontacts/ftw/contacts/tests/test_contact_folder_reload.py", line 184, in test_search_with_special_chars
    "The special chars are replaced with an empty string.")
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 521, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/raphael/Plone/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 514, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0 : There should be one contact, the 'Chuck 4orris'. The special chars are replaced with an empty string.
```
Here's a CI Job which failed with the same errors: https://ci.4teamwork.ch/builds/94975/tasks/139628

I don't know what exactly the problem is...

**Comment by mbaechtold** [comment] 2017-07-10 06:16
The problem is `collective.dexteritytextindexer 2.2.0` together with our test suite or `ftw.builder` (it works if you create content through the web), but I don't know exactly why. Will have to investigate and fix `collective.dexteritytextindexer`.

**Comment by jone** [comment] 2017-07-10 07:14
We didn't notice this problem because the nightly-builds of this package are not executed, see https://github.com/4teamwork/ci_governor/issues/93.

**Comment by mbaechtold** [comment] 2018-01-10 15:37
This seems no longer to be an issue, so I'm closing it.

**Closed by mbaechtold** 2018-01-10 15:37 UTC
